## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [80]:
import torch
import torch.nn as nn
from collections import OrderedDict


In [82]:
# your code here
#model1 = nn.Sequential(OrderedDict([
#    ('hidden', nn.
#]))

model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 4)),  # Input layer with 2 neurons, hidden layer with 4 neurons
    ('activation', nn.ReLU()),   # Activation function
    ('output', nn.Linear(4, 2)),  # Output layer with 1 neuron
    ('sigmoid', nn.Sigmoid()) 
]))

In [84]:
print(model1)

Sequential(
  (hidden): Linear(in_features=2, out_features=4, bias=True)
  (activation): ReLU()
  (output): Linear(in_features=4, out_features=2, bias=True)
  (sigmoid): Sigmoid()
)


In [86]:
# your code here
#data_in = torch.tensor( ...
data_in = torch.tensor([
    [0, 0],  
    [0, 1],  
    [1, 0],  
    [1, 1]   
], dtype=torch.float32)
print(data_in)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])


In [88]:
# your code here
# data_target = torch.tensor( ...
data_target = torch.tensor([
    [0, 0],  # 0 + 0 = 0 (sum, carry)
    [1, 0],  # 0 + 1 = 1
    [1, 0],  # 1 + 0 = 1
    [0, 1]   # 1 + 1 = 10
], dtype=torch.float32)
print(data_target)

tensor([[0., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.]])


In [90]:
# your code here
# criterion = 
# optimizer = 
criterion = nn.BCELoss()
optimizer = torch.optim.SGD(model1.parameters(), lr=0.1)


In [92]:
# your code here
# Train the model
def train_model(model, X, y, num_epoch=10000, lr=0.1):
    for epoch in range(num_epoch):
        outputs = model(X)
        loss = criterion(outputs, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if (epoch+1) % 500 == 0 : 
            print(f'Epoch [{epoch+1} / {num_epoch}], Loss: {loss.item():.4f}')

In [94]:
# your code here
# visualize the resuts
train_model(model1, data_in, data_target)

Epoch [500 / 10000], Loss: 0.2928
Epoch [1000 / 10000], Loss: 0.0782
Epoch [1500 / 10000], Loss: 0.0385
Epoch [2000 / 10000], Loss: 0.0246
Epoch [2500 / 10000], Loss: 0.0179
Epoch [3000 / 10000], Loss: 0.0139
Epoch [3500 / 10000], Loss: 0.0114
Epoch [4000 / 10000], Loss: 0.0096
Epoch [4500 / 10000], Loss: 0.0082
Epoch [5000 / 10000], Loss: 0.0072
Epoch [5500 / 10000], Loss: 0.0064
Epoch [6000 / 10000], Loss: 0.0058
Epoch [6500 / 10000], Loss: 0.0052
Epoch [7000 / 10000], Loss: 0.0048
Epoch [7500 / 10000], Loss: 0.0044
Epoch [8000 / 10000], Loss: 0.0041
Epoch [8500 / 10000], Loss: 0.0038
Epoch [9000 / 10000], Loss: 0.0036
Epoch [9500 / 10000], Loss: 0.0034
Epoch [10000 / 10000], Loss: 0.0032


In [96]:
# your code here
# print model wights
for name, param in model1.named_parameters():  
    print(f"{name}: \n{param.data}\n")

hidden.weight: 
tensor([[-3.4604,  3.4590],
        [ 2.5858, -3.6686],
        [-2.2770, -1.2306],
        [-0.2663, -0.0090]])

hidden.bias: 
tensor([ 3.1361e-04,  1.0817e+00,  2.7149e+00, -1.8050e-01])

output.weight: 
tensor([[ 4.2353,  3.3460, -2.1333, -0.3325],
        [-2.2516, -3.0765, -3.0728, -0.0635]])

output.bias: 
tensor([-4.6086,  4.5421])



In [98]:
def test_model(model, X, y):
    with torch.no_grad():
        outputs = model(X)
        predicted = (outputs > 0.5).float()  # Convert output to 0 or 1 (as the sigmoid output is between 0 and 1)
        correct = (predicted == y).float()  # Compare predicted output with target
        accuracy = correct.sum() / correct.numel()  # Calculate accuracy
        return accuracy

accuracy = test_model(model1, data_in, data_target)
print(f"Accuracy of Model 1: {accuracy:.4f}")

Accuracy of Model 1: 1.0000


In [191]:
# Model 2: 2 hidden layers 

model2 = nn.Sequential(OrderedDict([
    ('hidden1', nn.Linear(2, 3)),  # Input layer: 2 neurons, first hidden layer: 3 neurons
    ('activation1', nn.ReLU()),    # ReLU activation function for the first hidden layer
    ('hidden2', nn.Linear(3, 2)),  # Second hidden layer: 3 neurons, output layer: 2 neurons
    ('activation2', nn.ReLU()),    # ReLU activation function for the second hidden layer
    ('output', nn.Linear(2, 2)),   # Second hidden layer: 2 neurons, output layer: 2 neurons (sum and carry)
    ('sigmoid', nn.Sigmoid())      # Sigmoid activation function to get output between 0 and 1
]))

 #Input data (binary addition task)
data_in = torch.tensor([
    [0, 0],  
    [0, 1],  
    [1, 0],  
    [1, 1]   
], dtype=torch.float32)

# Target data (binary addition: sum and carry)
data_target = torch.tensor([
    [0, 0],  # 0 + 0 = 0 (sum, carry)
    [1, 0],  # 0 + 1 = 1 (sum, carry)
    [1, 0],  # 1 + 0 = 1 (sum, carry)
    [0, 1]   # 1 + 1 = 10 (sum, carry)
], dtype=torch.float32)

criterion = nn.BCELoss() 
optimizer = torch.optim.SGD(model2.parameters(), lr=0.01)

def train_model(model, X, y, num_epoch=10000, lr=0.01):
    for epoch in range(num_epoch):
        outputs = model(X)
        loss = criterion(outputs, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if (epoch+1) % 500 == 0 : 
            print(f'Epoch [{epoch+1} / {num_epoch}], Loss: {loss.item():.4f}')

train_model(model2, data_in, data_target)


#print the model weights
for name, param in model2.named_parameters():
    print(f"{name}: \n{param.data}\n")


def test_model(model, X, y):
    with torch.no_grad():
        outputs = model(X)
        predicted = (outputs > 0.5).float()  # Convert output to 0 or 1 (as the sigmoid output is between 0 and 1)
        correct = (predicted == y).float()  # Compare predicted output with target
        accuracy = correct.sum() / correct.numel()  # Calculate accuracy
        return accuracy

accuracy = test_model(model2, data_in, data_target)
print(f"Accuracy of Model 2: {accuracy:.4f}")

Epoch [500 / 10000], Loss: 0.6430
Epoch [1000 / 10000], Loss: 0.6257
Epoch [1500 / 10000], Loss: 0.6216
Epoch [2000 / 10000], Loss: 0.6185
Epoch [2500 / 10000], Loss: 0.6123
Epoch [3000 / 10000], Loss: 0.6006
Epoch [3500 / 10000], Loss: 0.5874
Epoch [4000 / 10000], Loss: 0.5719
Epoch [4500 / 10000], Loss: 0.5559
Epoch [5000 / 10000], Loss: 0.5418
Epoch [5500 / 10000], Loss: 0.5307
Epoch [6000 / 10000], Loss: 0.5222
Epoch [6500 / 10000], Loss: 0.5150
Epoch [7000 / 10000], Loss: 0.5082
Epoch [7500 / 10000], Loss: 0.5008
Epoch [8000 / 10000], Loss: 0.4923
Epoch [8500 / 10000], Loss: 0.4822
Epoch [9000 / 10000], Loss: 0.4705
Epoch [9500 / 10000], Loss: 0.4578
Epoch [10000 / 10000], Loss: 0.4453
hidden1.weight: 
tensor([[-0.6867,  0.2673],
        [ 1.2265, -1.7485],
        [-0.5727, -0.6017]])

hidden1.bias: 
tensor([-0.5518,  0.5141,  0.6015])

hidden2.weight: 
tensor([[-0.2939,  1.7980, -0.6066],
        [ 0.4978, -1.0364, -0.7213]])

hidden2.bias: 
tensor([0.4998, 0.9667])

output.weig

In [190]:
#Model 3: 3 hidden layers 

model3 = nn.Sequential(OrderedDict([
    ('hidden1', nn.Linear(2, 4)),  # Input layer: 2 neurons, first hidden layer: 4 neurons
    ('activation1', nn.ReLU()),    # ReLU activation function for the first hidden layer
    ('hidden2', nn.Linear(4, 3)),  # Second hidden layer: 4 neurons, third hidden layer: 3 neurons
    ('activation2', nn.ReLU()),    # ReLU activation function for the second hidden layer
    ('hidden3', nn.Linear(3, 2)),  # Third hidden layer: 3 neurons, output layer: 2 neurons
    ('activation3', nn.ReLU()),    # ReLU activation function for the third hidden layer
    ('output', nn.Linear(2, 2)),   # Output layer: 2 neurons (sum and carry)
    ('sigmoid', nn.Sigmoid())      # Sigmoid activation function to get output between 0 and 1
]))


# Input data (binary addition task)
data_in = torch.tensor([
    [0, 0],  
    [0, 1],  
    [1, 0],  
    [1, 1]   
], dtype=torch.float32)

# Target data (binary addition: sum and carry)
data_target = torch.tensor([
    [0, 0],  # 0 + 0 = 0 (sum, carry)
    [1, 0],  # 0 + 1 = 1 (sum, carry)
    [1, 0],  # 1 + 0 = 1 (sum, carry)
    [0, 1]   # 1 + 1 = 10 (sum, carry)
], dtype=torch.float32)

criterion = nn.BCELoss() 
optimizer = torch.optim.SGD(model3.parameters(), lr=0.01)

def train_model(model, X, y, num_epoch=10000, lr=0.01):
    for epoch in range(num_epoch):
        outputs = model(X)
        loss = criterion(outputs, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if (epoch+1) % 500 == 0 : 
            print(f'Epoch [{epoch+1} / {num_epoch}], Loss: {loss.item():.4f}')

train_model(model3, data_in, data_target)

#Print the model weights
for name, param in model3.named_parameters():
    print(f"{name}: \n{param.data}\n")



def test_model(model, X, y):
    with torch.no_grad():
        outputs = model(X)
        predicted = (outputs > 0.5).float()  # Convert output to 0 or 1 (as the sigmoid output is between 0 and 1)
        correct = (predicted == y).float()  # Compare predicted output with target
        accuracy = correct.sum() / correct.numel()  # Calculate accuracy
        return accuracy

accuracy = test_model(model3, data_in, data_target)
print(f"Accuracy of Model 3: {accuracy:.4f}")

Epoch [500 / 10000], Loss: 0.6604
Epoch [1000 / 10000], Loss: 0.6380
Epoch [1500 / 10000], Loss: 0.6312
Epoch [2000 / 10000], Loss: 0.6290
Epoch [2500 / 10000], Loss: 0.6282
Epoch [3000 / 10000], Loss: 0.6279
Epoch [3500 / 10000], Loss: 0.6278
Epoch [4000 / 10000], Loss: 0.6278
Epoch [4500 / 10000], Loss: 0.6277
Epoch [5000 / 10000], Loss: 0.6277
Epoch [5500 / 10000], Loss: 0.6277
Epoch [6000 / 10000], Loss: 0.6277
Epoch [6500 / 10000], Loss: 0.6277
Epoch [7000 / 10000], Loss: 0.6277
Epoch [7500 / 10000], Loss: 0.6277
Epoch [8000 / 10000], Loss: 0.6277
Epoch [8500 / 10000], Loss: 0.6277
Epoch [9000 / 10000], Loss: 0.6277
Epoch [9500 / 10000], Loss: 0.6277
Epoch [10000 / 10000], Loss: 0.6277
hidden1.weight: 
tensor([[-0.3257, -0.1885],
        [ 0.3922, -0.0351],
        [ 0.3660,  0.1609],
        [ 0.2310, -0.1298]])

hidden1.bias: 
tensor([ 0.0416,  0.5056, -0.3411, -0.2641])

hidden2.weight: 
tensor([[-0.2102, -0.2194, -0.3196,  0.2526],
        [-0.1988,  0.0425, -0.4157,  0.1124],